//! Internal proposal-tracking types and storage adapters.
//!
//! When a client calls [`NodeHandle::propose`](crate::NodeHandle::propose), the
//! supplied value is wrapped in a [`Pending`] envelope carrying a unique
//! `nonce`. The protocol layer (Paxos / Raft) operates on `Pending<V>` so that
//! the proposing node can match decided values back to the originating
//! [`Submission`] via the nonce, even when the value type itself is not unique.
//!
//! The nonce is purely a runtime concept: it travels on the wire (and in the
//! Raft log) so a decision's nonce can be matched against the proposing node's
//! pending map, but on-disk persistence drops the nonce. After recovery the
//! original requester is gone anyway, so a synthetic nonce is fine.

use async_trait::async_trait;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use tokio::sync::oneshot;

use crate::config::NodeId;
use crate::error::{ProposeError, StorageError};
use crate::message::LogEntry;
use crate::node::Decided;
use crate::storage::{PaxosStorage, RaftStorage};

/// Internal envelope around a user-supplied value.
///
/// Generated by [`NodeHandle::propose`](crate::NodeHandle::propose); the nonce
/// is unique per proposal (random `u64` — collisions across nodes are
/// vanishingly unlikely). The protocol layer treats `Pending<V>` as opaque
/// (serializable, cloneable, comparable for equality), which means two
/// proposals carrying the same `V` but different nonces are independently
/// tracked.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct Pending<V> {
    pub nonce: u64,
    pub value: V,
}

/// A proposal handed to the event loop.
///
/// Carries the wrapped value and a oneshot used to signal commit / cancellation
/// back to the caller of [`NodeHandle::propose`](crate::NodeHandle::propose).
pub(crate) struct Submission<V> {
    pub pending: Pending<V>,
    pub completion: oneshot::Sender<Result<Decided<V>, ProposeError>>,
}

/// Adapts a user-supplied [`PaxosStorage<V>`] into a [`PaxosStorage<Pending<V>>`].
///
/// `save_decision` drops the nonce before delegating; `load_decisions`
/// synthesizes a fresh nonce (which won't match any pending oneshot — the
/// proposer is presumed gone after restart).
pub(crate) struct PendingPaxosStorage<V, S> {
    inner: S,
    _marker: std::marker::PhantomData<V>,
}

impl<V, S> PendingPaxosStorage<V, S> {
    pub(crate) fn new(inner: S) -> Self {
        Self {
            inner,
            _marker: std::marker::PhantomData,
        }
    }
}

#[async_trait]
impl<V, S> PaxosStorage<Pending<V>> for PendingPaxosStorage<V, S>
where
    V: Serialize + DeserializeOwned + Clone + Send + Sync + 'static,
    S: PaxosStorage<V>,
{
    async fn save_decision(&mut self, slot: u64, value: Pending<V>) -> Result<(), StorageError> {
        self.inner.save_decision(slot, value.value).await
    }

    async fn load_decisions(&self) -> Result<Vec<(u64, Pending<V>)>, StorageError> {
        let raw = self.inner.load_decisions().await?;
        Ok(raw
            .into_iter()
            .map(|(slot, value)| (slot, Pending { nonce: 0, value }))
            .collect())
    }
}

/// Adapts a user-supplied [`RaftStorage<V>`] into a [`RaftStorage<Pending<V>>`].
pub(crate) struct PendingRaftStorage<V, S> {
    inner: S,
    _marker: std::marker::PhantomData<V>,
}

impl<V, S> PendingRaftStorage<V, S> {
    pub(crate) fn new(inner: S) -> Self {
        Self {
            inner,
            _marker: std::marker::PhantomData,
        }
    }
}

fn strip_log_entries<V: Clone>(entries: &[LogEntry<Pending<V>>]) -> Vec<LogEntry<V>> {
    entries
        .iter()
        .map(|e| LogEntry {
            term: e.term,
            value: e.value.value.clone(),
        })
        .collect()
}

fn wrap_log_entries<V>(entries: Vec<LogEntry<V>>) -> Vec<LogEntry<Pending<V>>> {
    entries
        .into_iter()
        .map(|e| LogEntry {
            term: e.term,
            value: Pending {
                nonce: 0,
                value: e.value,
            },
        })
        .collect()
}

#[async_trait]
impl<V, S> RaftStorage<Pending<V>> for PendingRaftStorage<V, S>
where
    V: Serialize + DeserializeOwned + Clone + Send + Sync + 'static,
    S: RaftStorage<V>,
{
    async fn save_decision(&mut self, slot: u64, value: Pending<V>) -> Result<(), StorageError> {
        self.inner.save_decision(slot, value.value).await
    }

    async fn load_decisions(&self) -> Result<Vec<(u64, Pending<V>)>, StorageError> {
        let raw = self.inner.load_decisions().await?;
        Ok(raw
            .into_iter()
            .map(|(slot, value)| (slot, Pending { nonce: 0, value }))
            .collect())
    }

    async fn save_term(&mut self, term: u64) -> Result<(), StorageError> {
        self.inner.save_term(term).await
    }

    async fn load_term(&self) -> Result<u64, StorageError> {
        self.inner.load_term().await
    }

    async fn save_voted_for(&mut self, voted_for: Option<NodeId>) -> Result<(), StorageError> {
        self.inner.save_voted_for(voted_for).await
    }

    async fn load_voted_for(&self) -> Result<Option<NodeId>, StorageError> {
        self.inner.load_voted_for().await
    }

    async fn append_log(&mut self, entries: &[LogEntry<Pending<V>>]) -> Result<(), StorageError> {
        let stripped = strip_log_entries(entries);
        self.inner.append_log(&stripped).await
    }

    async fn truncate_log_from(&mut self, index: u64) -> Result<(), StorageError> {
        self.inner.truncate_log_from(index).await
    }

    async fn load_log(&self) -> Result<Vec<LogEntry<Pending<V>>>, StorageError> {
        let raw = self.inner.load_log().await?;
        Ok(wrap_log_entries(raw))
    }

    async fn save_commit_index(&mut self, commit_index: Option<u64>) -> Result<(), StorageError> {
        self.inner.save_commit_index(commit_index).await
    }

    async fn load_commit_index(&self) -> Result<Option<u64>, StorageError> {
        self.inner.load_commit_index().await
    }
}
