apiVersion: v1
kind: Service
metadata:
  name: {{ include "daccord.fullname" . }}
  labels:
    {{- include "daccord.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "daccord.selectorLabels" . | nindent 4 }}
